name: docker_build_and_push
descripcion: to build and push image to dockerhub
inputs:
  pkg:
    required: true
    type: string
    default: code-server/micromamba
runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_USERNAME }}
    - run: |
      filename=${{ inputs.pkg }}
      pkgname="jojoroto/${filename/\//:}"
      docker build -f $filename -t $pkgname
      docker push $pkgname
