name: codercom_php8 docker Image CI

on:
  push:
    paths:
      'code-server/codercom_php8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jojoroto/code-server:codercom_php8
        file: code-server/codercom_php8
