name: build_micromamba
on:
  workflow_dispatch:

jobs:
  say:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - run: |
        filename="code-server/micromamba"
        pkgname="jojoroto/${filename/\//:}"
        docker build -f $filename -t $pkgname
        docker push $pkgname
